
// import dynamic from "next/dynamic";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Navbar";
import AuthProvider from "@/context/store";
// const Navbar = dynamic(() => import('../components/Navbar'), { ssr: false });
// const AuthProvider = dynamic(() => import("@/context/store"), { ssr: false });
// const Navbar = dynamic(() => import('../components/Navbar'), { ssr: false })

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Internship Recommendation System",
  description: "Generated by create next app",
};



export default function RootLayout({ children,pageProps }) {

  return (
       <AuthProvider >
    <html lang="en">
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#F8F9FA] px-10`} suppressHydrationWarning={true}
      >
       <div>
        <Navbar />
        {children}
       </div>
      </body>
    </html>
       </AuthProvider>
  );
}
