import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Navbar";
import AuthProvider from "@/context/store";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Footer from "@/components/Footer"; 

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Internship Recommendation System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#F8F9FA]`}
          suppressHydrationWarning={true}
        >
    <AuthProvider>
          <div className="flex flex-col min-h-screen">
            {/* Navbar */}
            <Navbar />
            
            {/* Main content area */}
            <main className="flex-grow mt-14">
              {children}
            </main>

            {/* Footer - push to the bottom */}
            <Footer className="mt-auto" />

            {/* Toast notifications */}
            <ToastContainer />
          </div>
    </AuthProvider>
        </body>
      </html>
  );
}
